[package]
name = "coactor"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
coactor-macros = { path = "../coactor-macros" }
futures-util.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["fmt"] }
trybuild = "1.0.105"

[[example]]
name = "counter"
path = "examples/counter.rs"
